### ISSUE TITLE
Dave compute test image build error

### ISSUE THREAD

**Issue by ZzzzHui** [cartesi/dave#51]
The command `docker build -t cartesi/dave-compute:test -f Dockerfile.compute.test ../../` in the `prt/compute-rs` folder fails on my machine (Apple M1), with some of the printed info as follows:
```
118.6   jsonrpc-virtual-machine.cpp:24:10: fatal error: mongoose.h: No such file or directory
118.6      24 | #include <mongoose.h>
118.6         |          ^~~~~~~~~~~~
118.6   compilation terminated.
118.6   make: *** [Makefile:546: jsonrpc-virtual-machine.o] Error 1
118.6   thread 'main' panicked at /app/machine/machine-rust-bindings/cartesi-machine-sys/build.rs:103:10:
118.6   Failed to move `libcartesi_jsonrpc.a` to OUT_DIR: Os { code: 2, kind: NotFound, message: "No such file or directory" }
118.6   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
118.7 thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-chef-0.1.67/src/recipe.rs:218:27:
118.7 Exited with status code: 101
118.7 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
------
Dockerfile.compute.test:22
--------------------
  20 |     # Build dependencies - this is the caching Docker layer!
  21 |     WORKDIR /app/prt/compute-rs
  22 | >>> RUN cargo chef cook --release --recipe-path recipe.json
  23 |     
  24 |     # Build application
--------------------
ERROR: failed to solve: process "/bin/sh -c cargo chef cook --release --recipe-path recipe.json" did not complete successfully: exit code: 101
```

Stephen debugged this error by removing all lines containing `jsonrpc` in the file `machine/machine-rust-bindings/cartesi-machine-sys/build.rs` and the build succeeded. Thanks @stephenctw

**Comment by stephenctw** [comment]
@GCdePaula I'm not sure what's the cause of this missing file error. But if we don't use `jsonrpc` anymore, can we simply remove those lines?

**Comment by stephenctw** [comment]
The issue seems to be that we copy local `machine-emulator` submodule into the docker image, but we didn't copy `.git` of the root directory. So `machine-emulator` find it inconsistent when it consider itself a submodule of someone else, but fail to find that parent `.git` directory when running `git submodule` command.

So I think there are several ways to solve this
1. We don't copy the local `machine-emulator` directory, but instead use `ADD` pointing to the git repo url so `machine-emulator` doesn't think itself is a git submodule.
2. We add `.git` of the root directory to all docker images, so `machine-emulator` can find its parent successfully.
3. Add instruction in `README` asking people to manually run `make dep` on his local `machine-emulator` before the docker build command.

What do you think?

solution 1: 
```
ADD --keep-git-dir=true https://github.com/cartesi/machine-emulator.git#v0.17.0 /app/machine/machine-emulator
```

solution 2:
```
COPY .git /app/.git
```
